### ISSUE TITLE
Can we get any easy way to switch between modview and regular view?

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#161] opened 2021-01-17 01:36 UTC
The current way of modding can be tedious at times.

**Comment by dedushka1** [comment] 2021-01-17 04:53
Can you be more specific about what you have in mind?

**Comment by dedushka1** [comment] 2021-01-17 22:27
Can we close this one and use #154 for this issue?

**Comment by nonmakina** [comment] 2021-01-17 23:44
As per comment above, this is a duplicate of #154

**Closed as completed by nonmakina** 2021-01-17 23:44 UTC
